import type { AssetFeatureCode, BusinessType } from "@prisma/client";

export type AssetSeed = {
  sellerEmail: string;
  slug: string;
  title: string;
  summary: string;
  description: string;
  jurisdictionCode: string;
  categoryCode: string;
  businessType: BusinessType;
  askingPriceEur: number | null;
  revenueEur: number | null;
  ebitdaEur: number | null;
  licenceStatus: "ACTIVE" | "IN_APPLICATION" | "DORMANT";
  regulator: string | null;
  licenceIssuedYear: number | null;
  yearEstablished: number | null;
  employees: number | null;
  activeClients: number | null;
  hasPassporting: boolean;
  reasonForSale: string | null;
  status: "DRAFT" | "PUBLISHED" | "UNDER_OFFER" | "SOLD" | "SUSPENDED" | "ARCHIVED";
  isValidated: boolean;
  viewCount: number;
  features: AssetFeatureCode[];
};

export const ASSETS: AssetSeed[] = [
  {
    sellerEmail: "seller@n5deal.demo",
    slug: "lithuanian-emi-full-passporting-since-2019",
    title: "Lithuanian EMI with full EEA passporting, trading since 2019",
    summary:
      "Bank of Lithuania authorised e-money institution with safeguarding in place, 4,200 active business clients and two IBAN providers.",
    description:
      "An operating electronic money institution authorised by the Bank of Lithuania in 2019. The company issues e-money, provides payment accounts with dedicated IBANs and operates SEPA Instant through a partner bank.\n\nThe entity passports into 14 EEA member states. Safeguarding accounts are held with two credit institutions. The compliance function is fully staffed with an MLRO approved by the regulator, and the team of eleven is expected to transfer with the business.\n\nThe last supervisory review closed without findings. Audited accounts for the past three financial years are available in the data room once an NDA is signed.",
    jurisdictionCode: "LT",
    categoryCode: "EMI",
    businessType: "PAYMENT",
    askingPriceEur: 2_400_000,
    revenueEur: 1_850_000,
    ebitdaEur: 410_000,
    licenceStatus: "ACTIVE",
    regulator: "Bank of Lithuania",
    licenceIssuedYear: 2019,
    yearEstablished: 2018,
    employees: 11,
    activeClients: 4_200,
    hasPassporting: true,
    reasonForSale:
      "The shareholder group is consolidating around its Nordic entity and is divesting the Baltic operation.",
    status: "PUBLISHED",
    isValidated: true,
    viewCount: 341,
    features: ["STAFF", "OFFICE", "BANK_ACCOUNTS", "MULTI_CURRENCY", "SOFTWARE_PLATFORM", "CLIENT_BASE"],
  },
  {
    sellerEmail: "seller@n5deal.demo",
    slug: "estonian-payment-institution-clean-shell",
    title: "Estonian payment institution, authorised and clean, no trading history",
    summary:
      "Authorised PI with no legacy clients and no operating history. Ready for a buyer who brings their own volume.",
    description:
      "A payment institution authorised by Finantsinspektsioon. The company has never onboarded clients, has no outstanding liabilities and has been maintained in good standing since authorisation.\n\nThis is a licence-only transaction. There is no team, no platform and no customer base — the value is the authorisation and the clean regulatory record. Suitable for a buyer with an existing product who needs permissions quickly.",
    jurisdictionCode: "EE",
    categoryCode: "PI",
    businessType: "PAYMENT",
    askingPriceEur: 620_000,
    revenueEur: 0,
    ebitdaEur: -45_000,
    licenceStatus: "DORMANT",
    regulator: "Finantsinspektsioon",
    licenceIssuedYear: 2022,
    yearEstablished: 2021,
    employees: 0,
    activeClients: 0,
    hasPassporting: true,
    reasonForSale: "Authorised for a product line the group ultimately did not launch.",
    status: "PUBLISHED",
    isValidated: true,
    viewCount: 188,
    features: ["BANK_ACCOUNTS"],
  },
  {
    sellerEmail: "broker.hk@n5deal.demo",
    slug: "hong-kong-mso-remittance-operating-since-2018",
    title: "Operating Hong Kong MSO with remittance and currency exchange since 2018",
    summary:
      "Customs & Excise licensed money service operator, profitable, with corridors into mainland China and Southeast Asia.",
    description:
      "A money service operator licensed by the Hong Kong Customs & Excise Department, trading continuously since 2018. The business runs both remittance and currency exchange, with established corridors into mainland China, the Philippines and Vietnam.\n\nThe company holds accounts with two Hong Kong banks — the single hardest thing to replicate for a new entrant. Office premises in Kwun Tong and six staff, including a licensed compliance officer, transfer with the business.",
    jurisdictionCode: "HK",
    categoryCode: "MSO",
    businessType: "PAYMENT",
    askingPriceEur: 1_150_000,
    revenueEur: 940_000,
    ebitdaEur: 265_000,
    licenceStatus: "ACTIVE",
    regulator: "Customs & Excise Department",
    licenceIssuedYear: 2018,
    yearEstablished: 2017,
    employees: 6,
    activeClients: 1_150,
    hasPassporting: false,
    reasonForSale: "The founder is retiring and has no succession within the family.",
    status: "PUBLISHED",
    isValidated: true,
    viewCount: 512,
    features: ["STAFF", "OFFICE", "BANK_ACCOUNTS", "MULTI_CURRENCY", "CLIENT_BASE"],
  },
  {
    sellerEmail: "broker.hk@n5deal.demo",
    slug: "singapore-major-payment-institution-in-application",
    title: "Singapore Major Payment Institution application at advanced stage",
    summary:
      "MAS application filed, first round of queries answered. Buyer steps into a live process rather than starting from zero.",
    description:
      "A Major Payment Institution application with the Monetary Authority of Singapore, filed and progressed through the first round of regulatory queries. The corporate vehicle, capital and appointed officers are in place.\n\nThe buyer assumes an application roughly nine months ahead of a fresh filing. Approval is not guaranteed and the sale is priced accordingly — this is explicitly a licence in application, not an authorised entity.",
    jurisdictionCode: "SG",
    categoryCode: "PI",
    businessType: "FINTECH",
    askingPriceEur: null,
    revenueEur: null,
    ebitdaEur: null,
    licenceStatus: "IN_APPLICATION",
    regulator: "Monetary Authority of Singapore",
    licenceIssuedYear: null,
    yearEstablished: 2023,
    employees: 2,
    activeClients: 0,
    hasPassporting: false,
    reasonForSale: "The sponsoring group changed its regional strategy mid-application.",
    status: "PUBLISHED",
    isValidated: false,
    viewCount: 97,
    features: ["OFFICE"],
  },
  {
    sellerEmail: "advisory.uk@n5deal.demo",
    slug: "uk-small-emi-fca-authorised-embedded-finance",
    title: "UK small electronic money institution, FCA authorised, embedded finance ready",
    summary:
      "Small EMI with a clean FCA record, modest volumes and an API-first platform already integrated with a UK card issuer.",
    description:
      "A small electronic money institution authorised by the Financial Conduct Authority. Volumes sit comfortably within the small EMI threshold, and the company has a clean supervisory history with no enforcement or past business reviews.\n\nThe technology stack is API-first and already integrated with a UK card issuing processor, which makes this a fast route to market for an embedded finance proposition. Two of the four staff are willing to stay through a transition period.",
    jurisdictionCode: "GB",
    categoryCode: "SEMI",
    businessType: "FINTECH",
    askingPriceEur: 780_000,
    revenueEur: 310_000,
    ebitdaEur: 40_000,
    licenceStatus: "ACTIVE",
    regulator: "Financial Conduct Authority",
    licenceIssuedYear: 2021,
    yearEstablished: 2020,
    employees: 4,
    activeClients: 380,
    hasPassporting: false,
    reasonForSale: "The founders are focusing on a separate lending business.",
    status: "PUBLISHED",
    isValidated: true,
    viewCount: 428,
    features: ["STAFF", "SOFTWARE_PLATFORM", "PAYMENT_RAILS", "CLIENT_BASE", "SECURITY_AUDIT"],
  },
  {
    sellerEmail: "advisory.uk@n5deal.demo",
    slug: "gibraltar-vasp-registration-with-banking",
    title: "Gibraltar DLT provider registration with active banking relationships",
    summary:
      "GFSC-registered distributed ledger technology provider, operational, with two European banking relationships in place.",
    description:
      "A distributed ledger technology provider registered with the Gibraltar Financial Services Commission. The entity is operational, files regularly and maintains two European banking relationships — unusual for the sector and a large part of the value here.\n\nThe buyer should expect a change-in-control process with the GFSC taking approximately four months.",
    jurisdictionCode: "GI",
    categoryCode: "VASP",
    businessType: "CRYPTO",
    askingPriceEur: 1_650_000,
    revenueEur: 720_000,
    ebitdaEur: 150_000,
    licenceStatus: "ACTIVE",
    regulator: "Gibraltar Financial Services Commission",
    licenceIssuedYear: 2020,
    yearEstablished: 2019,
    employees: 7,
    activeClients: 2_400,
    hasPassporting: false,
    reasonForSale: "Group consolidation into a single MiCA entity in the EU.",
    status: "PUBLISHED",
    isValidated: true,
    viewCount: 603,
    features: ["STAFF", "BANK_ACCOUNTS", "MULTI_CURRENCY", "SOFTWARE_PLATFORM", "CLIENT_BASE"],
  },
  {
    sellerEmail: "malta.owner@n5deal.demo",
    slug: "malta-casp-mica-authorised-exchange",
    title: "Malta CASP authorised under MiCA, exchange and custody permissions",
    summary:
      "MFSA-authorised crypto-asset service provider with exchange and custody permissions under the MiCA regime.",
    description:
      "A crypto-asset service provider authorised by the Malta Financial Services Authority under MiCA, holding permissions for exchange of crypto-assets for funds and for custody and administration on behalf of clients.\n\nThe entity has a functioning compliance framework, an approved MLRO and completed its first full MiCA reporting cycle. Passporting notifications have been filed for six member states.",
    jurisdictionCode: "MT",
    categoryCode: "CASP",
    businessType: "CRYPTO",
    askingPriceEur: 2_100_000,
    revenueEur: 1_050_000,
    ebitdaEur: 180_000,
    licenceStatus: "ACTIVE",
    regulator: "Malta Financial Services Authority",
    licenceIssuedYear: 2025,
    yearEstablished: 2021,
    employees: 9,
    activeClients: 5_800,
    hasPassporting: true,
    reasonForSale: "Shareholder restructuring following a group merger.",
    status: "PUBLISHED",
    isValidated: false,
    viewCount: 776,
    features: ["STAFF", "OFFICE", "MULTI_CURRENCY", "SOFTWARE_PLATFORM", "CLIENT_BASE", "SECURITY_AUDIT"],
  },
  {
    sellerEmail: "malta.owner@n5deal.demo",
    slug: "cyprus-investment-firm-mifid-cysec",
    title: "Cyprus investment firm with MiFID permissions, CySEC supervised",
    summary:
      "CIF licence covering reception and transmission of orders, execution and portfolio management. Price on request.",
    description:
      "A Cyprus investment firm supervised by CySEC, holding MiFID permissions for reception and transmission of orders, execution of orders on behalf of clients, and portfolio management.\n\nThe firm has an established institutional client base and passports across the EU. Pricing is on request and will depend on whether the buyer takes the client book or the licence alone.",
    jurisdictionCode: "CY",
    categoryCode: "INV",
    businessType: "FOREX",
    askingPriceEur: null,
    revenueEur: 2_300_000,
    ebitdaEur: 520_000,
    licenceStatus: "ACTIVE",
    regulator: "CySEC",
    licenceIssuedYear: 2017,
    yearEstablished: 2016,
    employees: 18,
    activeClients: 890,
    hasPassporting: true,
    reasonForSale: "Owners exiting the CFD sector entirely.",
    status: "PUBLISHED",
    isValidated: true,
    viewCount: 254,
    features: ["STAFF", "OFFICE", "BANK_ACCOUNTS", "CLIENT_BASE"],
  },
  {
    sellerEmail: "seller@n5deal.demo",
    slug: "latvian-payment-institution-under-offer",
    title: "Latvian payment institution with Baltic merchant acquiring book",
    summary:
      "Operating PI with an acquiring book across the Baltics. Currently under offer, exclusivity ends next month.",
    description:
      "A payment institution licensed by Latvijas Banka with an established merchant acquiring book across Latvia, Lithuania and Estonia.\n\nThe asset is currently under offer with exclusivity running to the end of the month. Back-up offers are being recorded in case the process does not complete.",
    jurisdictionCode: "LV",
    categoryCode: "PI",
    businessType: "PAYMENT",
    askingPriceEur: 1_900_000,
    revenueEur: 1_400_000,
    ebitdaEur: 320_000,
    licenceStatus: "ACTIVE",
    regulator: "Latvijas Banka",
    licenceIssuedYear: 2020,
    yearEstablished: 2019,
    employees: 8,
    activeClients: 640,
    hasPassporting: true,
    reasonForSale: "Founder exit.",
    status: "UNDER_OFFER",
    isValidated: true,
    viewCount: 389,
    features: ["STAFF", "BANK_ACCOUNTS", "PAYMENT_RAILS", "CLIENT_BASE"],
  },
  {
    sellerEmail: "advisory.uk@n5deal.demo",
    slug: "irish-emi-sold-2025",
    title: "Irish e-money institution with SEPA and card issuing",
    summary: "Central Bank of Ireland authorised EMI. Transaction completed — retained for reference.",
    description:
      "An electronic money institution authorised by the Central Bank of Ireland with SEPA access and a card issuing programme. This transaction has completed; the listing is retained so that comparable pricing stays visible to the market.",
    jurisdictionCode: "IE",
    categoryCode: "EMI",
    businessType: "PAYMENT",
    askingPriceEur: 4_200_000,
    revenueEur: 3_100_000,
    ebitdaEur: 740_000,
    licenceStatus: "ACTIVE",
    regulator: "Central Bank of Ireland",
    licenceIssuedYear: 2018,
    yearEstablished: 2017,
    employees: 22,
    activeClients: 9_400,
    hasPassporting: true,
    reasonForSale: "Strategic exit.",
    status: "SOLD",
    isValidated: true,
    viewCount: 1_204,
    features: ["STAFF", "OFFICE", "BANK_ACCOUNTS", "MULTI_CURRENCY", "SOFTWARE_PLATFORM", "PAYMENT_RAILS", "CLIENT_BASE"],
  },
  {
    sellerEmail: "broker.hk@n5deal.demo",
    slug: "australian-afsl-remittance-draft",
    title: "Australian remittance business with AUSTRAC registration",
    summary: "Draft listing — financials still being confirmed with the seller.",
    description:
      "An AUSTRAC-registered remittance network provider operating corridors into the Pacific. The seller is still assembling audited figures, so this listing has not been published yet.",
    jurisdictionCode: "AU",
    categoryCode: "MTL",
    businessType: "PAYMENT",
    askingPriceEur: 480_000,
    revenueEur: null,
    ebitdaEur: null,
    licenceStatus: "ACTIVE",
    regulator: "AUSTRAC",
    licenceIssuedYear: 2019,
    yearEstablished: 2018,
    employees: 3,
    activeClients: 210,
    hasPassporting: false,
    reasonForSale: "Owner relocating.",
    status: "DRAFT",
    isValidated: false,
    viewCount: 0,
    features: ["CLIENT_BASE"],
  },
  {
    sellerEmail: "flagged.seller@n5deal.demo",
    slug: "panama-financial-licence-fast-transfer",
    title: "Panama financial licence, guaranteed transfer in 48 hours",
    summary: "Removed from the marketplace by a platform manager.",
    description:
      "Fast licence transfer with no due diligence requirements and no source of funds documentation. Payment in cash or crypto accepted.",
    jurisdictionCode: "PA",
    categoryCode: "VASP",
    businessType: "OTHER",
    askingPriceEur: 95_000,
    revenueEur: null,
    ebitdaEur: null,
    licenceStatus: "DORMANT",
    regulator: null,
    licenceIssuedYear: 2023,
    yearEstablished: 2023,
    employees: 0,
    activeClients: 0,
    hasPassporting: false,
    reasonForSale: null,
    status: "SUSPENDED",
    isValidated: false,
    viewCount: 46,
    features: [],
  },
  {
    sellerEmail: "seller@n5deal.demo",
    slug: "polish-small-payment-institution-fintech",
    title: "Polish small payment institution serving e-commerce merchants",
    summary:
      "KNF-registered small payment institution with an e-commerce merchant base and an in-house checkout product.",
    description:
      "A small payment institution registered with the Polish Financial Supervision Authority, serving mid-sized e-commerce merchants with an in-house checkout and reconciliation product.\n\nVolumes are approaching the small payment institution threshold, so the natural next step for a buyer is a full authorisation — the groundwork for that filing has already been prepared.",
    jurisdictionCode: "PL",
    categoryCode: "SPI",
    businessType: "FINTECH",
    askingPriceEur: 540_000,
    revenueEur: 380_000,
    ebitdaEur: 62_000,
    licenceStatus: "ACTIVE",
    regulator: "KNF",
    licenceIssuedYear: 2021,
    yearEstablished: 2020,
    employees: 5,
    activeClients: 310,
    hasPassporting: false,
    reasonForSale: "The team wants to focus on software rather than regulated operations.",
    status: "PUBLISHED",
    isValidated: false,
    viewCount: 172,
    features: ["STAFF", "SOFTWARE_PLATFORM", "CLIENT_BASE"],
  },
  {
    sellerEmail: "malta.owner@n5deal.demo",
    slug: "bulgarian-emi-with-multicurrency-iban",
    title: "Bulgarian EMI issuing multi-currency IBANs across the EEA",
    summary:
      "BNB authorised e-money institution with multi-currency IBAN issuance and a corporate client base.",
    description:
      "An electronic money institution authorised by the Bulgarian National Bank, issuing multi-currency IBANs to corporate clients across the EEA under passporting.\n\nThe operation is lean and profitable, with a compliance team of three and an outsourced technology stack that transfers with the entity.",
    jurisdictionCode: "BG",
    categoryCode: "EMI",
    businessType: "PAYMENT",
    askingPriceEur: 1_320_000,
    revenueEur: 860_000,
    ebitdaEur: 195_000,
    licenceStatus: "ACTIVE",
    regulator: "Bulgarian National Bank",
    licenceIssuedYear: 2020,
    yearEstablished: 2019,
    employees: 6,
    activeClients: 1_900,
    hasPassporting: true,
    reasonForSale: "Shareholder liquidity event.",
    status: "PUBLISHED",
    isValidated: true,
    viewCount: 311,
    features: ["STAFF", "BANK_ACCOUNTS", "MULTI_CURRENCY", "CLIENT_BASE"],
  },
  {
    sellerEmail: "advisory.uk@n5deal.demo",
    slug: "uae-payment-services-provider-adgm",
    title: "ADGM payment services provider with regional corridor volume",
    summary:
      "FSRA-regulated payment services provider in Abu Dhabi Global Market with live Gulf-to-Europe corridors.",
    description:
      "A payment services provider regulated by the Financial Services Regulatory Authority in ADGM, running live corridors between the Gulf and Europe.\n\nThe business is majority corporate flow, with the top five clients accounting for roughly 40% of volume — a concentration a buyer should price in.",
    jurisdictionCode: "AE",
    categoryCode: "PI",
    businessType: "PAYMENT",
    askingPriceEur: 3_400_000,
    revenueEur: 2_050_000,
    ebitdaEur: 480_000,
    licenceStatus: "ACTIVE",
    regulator: "ADGM FSRA",
    licenceIssuedYear: 2021,
    yearEstablished: 2020,
    employees: 14,
    activeClients: 420,
    hasPassporting: false,
    reasonForSale: "Founders exiting to focus on an asset management venture.",
    status: "PUBLISHED",
    isValidated: true,
    viewCount: 495,
    features: ["STAFF", "OFFICE", "BANK_ACCOUNTS", "MULTI_CURRENCY", "PAYMENT_RAILS", "CLIENT_BASE"],
  },
];
