export const JURISDICTIONS = [
  { code: "LT", name: "Lithuania", region: "EU" },
  { code: "MT", name: "Malta", region: "EU" },
  { code: "CY", name: "Cyprus", region: "EU" },
  { code: "IE", name: "Ireland", region: "EU" },
  { code: "NL", name: "Netherlands", region: "EU" },
  { code: "LU", name: "Luxembourg", region: "EU" },
  { code: "EE", name: "Estonia", region: "EU" },
  { code: "LV", name: "Latvia", region: "EU" },
  { code: "PL", name: "Poland", region: "EU" },
  { code: "CZ", name: "Czechia", region: "EU" },
  { code: "BG", name: "Bulgaria", region: "EU" },
  { code: "ES", name: "Spain", region: "EU" },
  { code: "DE", name: "Germany", region: "EU" },
  { code: "FR", name: "France", region: "EU" },
  { code: "SE", name: "Sweden", region: "EU" },
  { code: "DK", name: "Denmark", region: "EU" },
  { code: "NO", name: "Norway", region: "EEA" },
  { code: "IS", name: "Iceland", region: "EEA" },
  { code: "LI", name: "Liechtenstein", region: "EEA" },
  { code: "CH", name: "Switzerland", region: "EEA" },
  { code: "GB", name: "United Kingdom", region: "UK" },
  { code: "GI", name: "Gibraltar", region: "UK" },
  { code: "JE", name: "Jersey", region: "OFFSHORE" },
  { code: "IM", name: "Isle of Man", region: "OFFSHORE" },
  { code: "KY", name: "Cayman Islands", region: "OFFSHORE" },
  { code: "BVI", name: "British Virgin Islands", region: "OFFSHORE" },
  { code: "HK", name: "Hong Kong", region: "APAC" },
  { code: "SG", name: "Singapore", region: "APAC" },
  { code: "AU", name: "Australia", region: "APAC" },
  { code: "NZ", name: "New Zealand", region: "APAC" },
  { code: "JP", name: "Japan", region: "APAC" },
  { code: "AE", name: "United Arab Emirates", region: "MENA" },
  { code: "BH", name: "Bahrain", region: "MENA" },
  { code: "US", name: "United States", region: "NORTH_AMERICA" },
  { code: "CA", name: "Canada", region: "NORTH_AMERICA" },
  { code: "MX", name: "Mexico", region: "LATAM" },
  { code: "BR", name: "Brazil", region: "LATAM" },
  { code: "PA", name: "Panama", region: "LATAM" },
];

export const CATEGORIES = [
  {
    code: "EMI",
    name: "Electronic Money Institution",
    description: "Full e-money issuance and payment accounts.",
  },
  { code: "SEMI", name: "Small EMI", description: "Volume-capped e-money licence." },
  {
    code: "PI",
    name: "Payment Institution",
    description: "Payment services without e-money issuance.",
  },
  {
    code: "SPI",
    name: "Small Payment Institution",
    description: "Volume-capped payment institution.",
  },
  { code: "BANK", name: "Banking Licence", description: "Full credit institution." },
  {
    code: "CASP",
    name: "Crypto-Asset Service Provider",
    description: "MiCA-scope crypto services.",
  },
  {
    code: "VASP",
    name: "Virtual Asset Service Provider",
    description: "Pre-MiCA / non-EU crypto registration.",
  },
  {
    code: "MSO",
    name: "Money Service Operator",
    description: "Hong Kong remittance and currency exchange.",
  },
  {
    code: "MTL",
    name: "Money Transmitter Licence",
    description: "US state-level money transmission.",
  },
  { code: "INV", name: "Investment Firm", description: "MiFID II investment services." },
  { code: "FX", name: "FX / CFD Brokerage", description: "Retail and institutional FX brokerage." },
  { code: "INSUR", name: "Insurance Intermediary", description: "Insurance distribution licence." },
];
